<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Details</title>
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/sweetalert2.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
 
</head>
<body>
   <?php include 'header.php'; ?>


    <!-- Blog Section Start -->
<section class="why-choose">
        <div class="container">
           <div class="text-center w-100 d-flex flex-column   mb-3">
            <div class="d-flex align-items-center gap-3">
                <a href="blog" style="color: #025ba8;"><i class="fa-solid fa-arrow-left fs-4"></i></a>
            <h2 class="section-title text-start fs-1 mb-0">Blog Details</h2>
            </div>
        
           </div>


           <div class="row g-3 position-relative">
                <div class="col-lg-9 col-12">
                     
                        <div class="w-100 d-flex flex-column align-items-start justify-content-center">
                        <h5 class="mb-3 fs-2 head-title-blog">How Financial Consulting Can Boost Your Small Business Growth</h5>
                         
                        </div>
                        
                    </div>  
                    <div class="d-lg-flex flex-lg-row flex-column align-items-center gap-2 position-relative time-box-spanvl">

                         <span>lorem Impsum</span> <p class="one"></p>
                            <span>February 15, 2026</span><p class="two"></p>
                        <span class="third-party-time">2 min read</span> 
                    </div>
                </div>


                <div class="mt-3 row">

                    <div class="inner-big-img">
                        <img src="./assets/images/contact-left-img.png" alt="inner-thumbnail-img" class="w-100 h-100 object-fit-cover rounded-2 mb-3">
                    </div>

                    <div class="col-12 d-flex align-items-start flex-column mt-5">
                    <h4 class="text-dark mb-3">1. Purpose and Scope</h4>
                    <p>Relievy Automation ('we", 'us", 'our') provides automated data processing tools specifically designed to assist finance teams, audit professionals, and related practitioners in streamlining manual workflows. Our solutions convert PDF documents into well-formatted Excel sheets, merge multiple Excel sheets or workbooks, and perform similar transformations on structured and unstructured financial data.</p>
                    <p>We recognize that the information processed through our tools often includes highly sensitive financial records-such as bank statements, Form 26AS tax statements, ledgers and other workbooks containing transactional or personally identifiable financial information. This Policy establishes our binding commitment to the complete privacy, confidentiality, and secure deletion of all such data.
                    </p>
                    <p class="mb-0">This Policy applies to all tools, web applications, and related services offered under the Relievy Automation brand. It governs the collection, use, retention, and deletion of any data uploaded or generated through our services.</p>
                </div>


                 <div class="col-12 d-flex align-items-start flex-column mt-5">
                    <h4 class="text-dark mb-3">  2. Definitions For the purposes of this Policy:</h4>
                    <p><strong class="text-dark">Data</strong> means any file, document, image, spreadsheet, or other digital content uploaded, submitted, or generated by a User through our tools. This includes, but is not limited to, PDF bank statements, 26AS tax forms, Excel workbooks, CSV files, and any metadata embedded therein.</p>
                    <p><strong class="text-dark">"Job" </strong>means a single processing transaction initiated by a User, consisting of the upload of Data, the automated operation performed by our tool, and the delivery of the processed result.
                    </p>
                    <p  ><strong class="text-dark">"User"</strong> means any individual or entity that accesses or uses any tool provided by Relievy Automation.</p>
                    <p  ><strong class="text-dark">"Temporary Storage"</strong> means any volatile or non-volatile storage used solely to facilitate the completion of a Job, from which Data is purged either immediately upon Job completion or within the maximum retention period defined in Section 6.</p>
                    <p  ><strong class="text-dark">"Permanent Deletion"</strong> means the complete, irreversible removal of Data from all active systems, including all production servers, backup media, caches, and disaster recovery environments, such that no copy remains accessible or restorable.</p>
                </div>

                </div>
                
           </div>
           
            
        </div>
        </section>

    <!-- Blog Section End -->

 <?php include 'footer.php'; ?>
     <script src="assets/js/jquery.min.js"></script>
     <script src="assets/js/script.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/sweetalert.min.js"></script>
    <script src="assets/js/toast.js"></script>
</body>

</html>